/**
 * ASS Writer — reconstructs a valid ASS file from parsed AssTrack
 * Used for resample mode when outputting .ass format
 */

import { formatAssTimestamp } from "./ass-parser"
import type { AssEvent, AssStyle, AssTrack } from "./ass-parser"

/**
 * Write an AssTrack back to ASS format string
 */
export function writeAss(track: AssTrack): string {
    const lines: string[] = []

    // [Script Info]
    lines.push("[Script Info]")
    lines.push(`; Script generated by Yuuume Ass Converter (https://github.com/yuramedia/convert)`)
    lines.push(`Title: ${track.scriptInfo.Title || "Yuuume Ass Converter (https://github.com/yuramedia/convert)"}`)
    lines.push(`ScriptType: ${track.scriptInfo.ScriptType || "v4.00+"}`)
    lines.push(`PlayResX: ${track.scriptInfo.PlayResX}`)
    lines.push(`PlayResY: ${track.scriptInfo.PlayResY}`)
    lines.push(`WrapStyle: ${track.scriptInfo.WrapStyle}`)
    lines.push(`ScaledBorderAndShadow: ${track.scriptInfo.ScaledBorderAndShadow ? "yes" : "no"}`)

    if (track.scriptInfo.Timer !== 100.0) {
        lines.push(`Timer: ${track.scriptInfo.Timer}`)
    }
    if (track.scriptInfo.YCbCrMatrix) {
        lines.push(`YCbCr Matrix: ${track.scriptInfo.YCbCrMatrix}`)
    }
    if (track.scriptInfo.Kerning) {
        lines.push(`Kerning: yes`)
    }
    if (track.scriptInfo.LayoutResX) {
        lines.push(`LayoutResX: ${track.scriptInfo.LayoutResX}`)
    }
    if (track.scriptInfo.LayoutResY) {
        lines.push(`LayoutResY: ${track.scriptInfo.LayoutResY}`)
    }

    // Write any extra script info fields
    for (const [key, value] of Object.entries(track.scriptInfo)) {
        const knownKeys = [
            "Title",
            "ScriptType",
            "PlayResX",
            "PlayResY",
            "WrapStyle",
            "ScaledBorderAndShadow",
            "Timer",
            "YCbCrMatrix",
            "Kerning",
            "LayoutResX",
            "LayoutResY"
        ]
        if (!knownKeys.includes(key) && typeof value === "string") {
            lines.push(`${key}: ${value}`)
        }
    }

    lines.push("")

    // [V4+ Styles]
    const styleSection = track.trackType === "SSA" ? "[V4 Styles]" : "[V4+ Styles]"
    lines.push(styleSection)

    // Format line
    const styleFormat =
        track.styleFormat.length > 0
            ? track.styleFormat
            : [
                  "Name",
                  "Fontname",
                  "Fontsize",
                  "PrimaryColour",
                  "SecondaryColour",
                  "OutlineColour",
                  "BackColour",
                  "Bold",
                  "Italic",
                  "Underline",
                  "StrikeOut",
                  "ScaleX",
                  "ScaleY",
                  "Spacing",
                  "Angle",
                  "BorderStyle",
                  "Outline",
                  "Shadow",
                  "Alignment",
                  "MarginL",
                  "MarginR",
                  "MarginV",
                  "Encoding"
              ]

    lines.push(`Format: ${styleFormat.join(", ")}`)

    for (const style of track.styles) {
        const values = styleFormat.map(field => {
            return getStyleFieldValue(style, field)
        })
        lines.push(`Style: ${values.join(",")}`)
    }

    lines.push("")

    // [Events]
    lines.push("[Events]")

    const eventFormat =
        track.eventFormat.length > 0
            ? track.eventFormat
            : ["Layer", "Start", "End", "Style", "Name", "MarginL", "MarginR", "MarginV", "Effect", "Text"]

    lines.push(`Format: ${eventFormat.join(", ")}`)

    for (const event of track.events) {
        const values = eventFormat.map(field => {
            return getEventFieldValue(event, field)
        })
        lines.push(`${event.type}: ${values.join(",")}`)
    }

    lines.push("")

    // Raw sections (Fonts, Graphics, etc.)
    for (const section of track.rawSections) {
        lines.push(section.name)
        for (const line of section.lines) {
            lines.push(line)
        }
        lines.push("")
    }

    return lines.join("\n")
}

function getStyleFieldValue(style: AssStyle, field: string): string {
    const fieldLower = field.toLowerCase()

    // Try raw values first for lossless roundtrip
    if (style._raw && typeof style._raw === "object") {
        const raw = style._raw as Record<string, string>
        if (raw[field] !== undefined) return raw[field]
    }

    switch (fieldLower) {
        case "name":
            return String(style.Name ?? "Default")
        case "fontname":
            return String(style.FontName ?? "Arial")
        case "fontsize":
            return String(style.FontSize ?? 18)
        case "primarycolour":
            return String(style.PrimaryColour ?? "&H00FFFFFF")
        case "secondarycolour":
            return String(style.SecondaryColour ?? "&H0000FFFF")
        case "outlinecolour":
        case "tertiarycolour":
            return String(style.OutlineColour ?? "&H00000000")
        case "backcolour":
            return String(style.BackColour ?? "&H00000080")
        case "bold":
            return (style.Bold as boolean) ? "-1" : "0"
        case "italic":
            return (style.Italic as boolean) ? "-1" : "0"
        case "underline":
            return (style.Underline as boolean) ? "-1" : "0"
        case "strikeout":
            return (style.StrikeOut as boolean) ? "-1" : "0"
        case "scalex":
            return String(style.ScaleX ?? 100)
        case "scaley":
            return String(style.ScaleY ?? 100)
        case "spacing":
            return String(style.Spacing ?? 0)
        case "angle":
            return String(style.Angle ?? 0)
        case "borderstyle":
            return String(style.BorderStyle ?? 1)
        case "outline":
            return String(style.Outline ?? 0)
        case "shadow":
            return String(style.Shadow ?? 0)
        case "alignment":
            return String(style.Alignment ?? 2)
        case "marginl":
            return String(style.MarginL ?? 0)
        case "marginr":
            return String(style.MarginR ?? 0)
        case "marginv":
            return String(style.MarginV ?? 0)
        case "encoding":
            return String(style.Encoding ?? 0)
        default:
            return "0"
    }
}

function getEventFieldValue(event: AssEvent, field: string): string {
    const fieldLower = field.toLowerCase()

    switch (fieldLower) {
        case "layer":
        case "marked":
            return String(event.Layer ?? 0)
        case "start":
            return formatAssTimestamp((event.Start as number) ?? 0)
        case "end":
            return formatAssTimestamp((event.End as number) ?? 0)
        case "style":
            return String(event.Style ?? "Default")
        case "name":
        case "actor":
            return String(event.Name ?? "")
        case "marginl":
            return String(event.MarginL ?? 0).padStart(4, "0")
        case "marginr":
            return String(event.MarginR ?? 0).padStart(4, "0")
        case "marginv":
            return String(event.MarginV ?? 0).padStart(4, "0")
        case "effect":
            return String(event.Effect ?? "")
        case "text":
            return String(event.Text ?? "")
        default:
            return ""
    }
}
